### ISSUE TITLE
rewrite_string is munging the lines

### ISSUE THREAD

**Issue by atoomic** [xsawyerx/ref-util-rewriter#5]
As shown with the one-liner below it seems that rewrite_string is losing the beginning of the line, we should expect `my $code =  is_coderef($foo)`

```
> perl -MRef::Util::Rewriter -E 'say Ref::Util::Rewriter::rewrite_string( q[ my $code = ref($foo) eq "CODE"] ); '
 is_coderef($foo)
```

**Comment by xsawyerx** [comment]
With the merged fixes, I think this is resolved. (Tried running the code and it doesn't trim it.)
